### PR TITLE
[26.04_linux-nvidia-bos] Backport upstream fixes for the vfio/pci and iommufd dma-buf series

### PR DESCRIPTION
**Pull request by kelsey-steele**
# Summary

These fixes target the vfio/pci and iommufd dma-buf series, which the NVIDIA [Patches and Configurations Guide](https://docs.nvidia.com/dccpu/patches-config-guide/virt-platform-software-patches-config_grace.html) lists under Host Kernel I/O Virtualization: Core SMMU as required for Grace virtualization. The series are already in this tree; this PR adds the upstream fixes to them. The important fixes here will be added to the patch guide next.

7 Fixes (upstream SHAs):

```
1a8a5227f229 vfio: Wait for dma-buf invalidation to complete
951ebc18d181 PCI/P2PDMA: Avoid returning a provider for non_mappable_bars
f2d70dbd3dce iommufd: Destroy the pages content after detaching from dmabuf
298ab7e6f163 iommufd: Clarify IOAS_MAP_FILE dma-buf support
c64a647c84f3 vfio/pci: fix dma-buf kref underflow after revoke
dba4254e216d iommufd/selftest: Fix dmabuf leak in iommufd_test_dmabuf_get()
5f3fc0ad9a41 iommufd: Reject DMABUF pages from the access pin path
```

2 Prerequisites (upstream SHAs):

```
95308225e5ba dma-buf: Rename dma_buf_move_notify() to dma_buf_invalidate_mappings()
61c0f69a2ff79 RDMA/uverbs: Update for semantic conflict with drm-misc
```

`1a8a5227f229` does not apply cleanly without the rename. It is included so every patch
here stays a clean cherry-pick, rather than hand-adapting a fix to the old symbol name.
Upstream split the rename across two commits — `95308225e5ba` covers dma-buf core and
the DRM callers, `61c0f69a2ff79` covers the RDMA callers. Both are required on this
branch or the build fails with `implicit declaration of function 'dma_buf_move_notify'`
in `drivers/infiniband/core/`.

8 of the 9 patches are clean cherry-picks. `951ebc18d181` is marked as a backport only
due to context change. Upstream's hunk does not carry the adjacent `aspm_os_control`
field present on this branch. The patch content itself is unchanged.

# Testing

- Clean build of both `nvidia` and `nvidia-64k` flavors
- Booted `nvidia-64k` on a GH200 running Ubuntu 26.04
- No regressions found through dmesg

LP: https://bugs.launchpad.net/bugs/2167041

### CODE REVIEW

**Comment by nirmoy** [comment]
## BaseOS Kernel Review

> [!NOTE]
> ### 🔄 Review in progress
> Boro is reviewing this pull request. Results will appear here when ready.

### 🔍 Review artifacts

- 🟡 **Boro review:** in progress

<details>
<summary><strong>Review metadata</strong></summary>

- Reviewed head: `805180d2b17e`
- Overall status: **in progress**

</details>

_This comment is maintained by BaseOS Reviewer and updated when the GitHub watcher publishes a newer review._

**Comment by jamieNguyenNVIDIA** [comment]
`Acked-by: Jamie Nguyen <jamien@nvidia.com>`

**Comment by clsotog** [comment]
`Acked-by: Carol L Soto <csoto@nvidia.com>`

**Comment by nvmochs** [comment]
Merged, closing PR.

```
89a8d5ee687e (nresolute/nvidia-bos-next) iommufd: Reject DMABUF pages from the access pin path
07f627574cc9 iommufd/selftest: Fix dmabuf leak in iommufd_test_dmabuf_get()
650920d7936f vfio/pci: fix dma-buf kref underflow after revoke
89463fde1da9 iommufd: Clarify IOAS_MAP_FILE dma-buf support
2b3af8f42335 iommufd: Destroy the pages content after detaching from dmabuf
9e3ec648b3a0 PCI/P2PDMA: Avoid returning a provider for non_mappable_bars
8411cf49b5cb vfio: Wait for dma-buf invalidation to complete
3bbee50e05b3 RDMA/uverbs: Update for semantic conflict with drm-misc
8f9502751bd3 dma-buf: Rename dma_buf_move_notify() to dma_buf_invalidate_mappings()
```
