### PR TITLE
[26.04_linux-nvidia] Backport upstream fixes for the vfio/pci and iommufd dma-buf series

### PR DESCRIPTION
**Pull request by kelsey-steele**
# Summary

These fixes target the vfio/pci and iommufd dma-buf series, which the NVIDIA [Patches and Configurations Guide](https://docs.nvidia.com/dccpu/patches-config-guide/virt-platform-software-patches-config_grace.html) lists under Host Kernel I/O Virtualization: Core SMMU as required for Grace virtualization. The series are already in this tree; this PR adds the upstream fixes to them. The important fixes here will be added to the patch guide next.

7 Fixes (upstream SHAs):

```
1a8a5227f229 vfio: Wait for dma-buf invalidation to complete
951ebc18d181 PCI/P2PDMA: Avoid returning a provider for non_mappable_bars
f2d70dbd3dce iommufd: Destroy the pages content after detaching from dmabuf
298ab7e6f163 iommufd: Clarify IOAS_MAP_FILE dma-buf support
c64a647c84f3 vfio/pci: fix dma-buf kref underflow after revoke
dba4254e216d iommufd/selftest: Fix dmabuf leak in iommufd_test_dmabuf_get()
5f3fc0ad9a41 iommufd: Reject DMABUF pages from the access pin path
```

2 Prerequisites (upstream SHAs):

```
95308225e5ba dma-buf: Rename dma_buf_move_notify() to dma_buf_invalidate_mappings()
61c0f69a2ff79 RDMA/uverbs: Update for semantic conflict with drm-misc
```

`1a8a5227f229` does not apply cleanly without the rename. It is included so every patch
here stays a clean cherry-pick, rather than hand-adapting a fix to the old symbol name.
Upstream split the rename across two commits — `95308225e5ba` covers dma-buf core and
the DRM callers, `61c0f69a2ff79` covers the RDMA callers. Both are required on this
branch or the build fails with `implicit declaration of function 'dma_buf_move_notify'`
in `drivers/infiniband/core/`.

8 of the 9 patches are clean cherry-picks. `951ebc18d181` is marked as a backport only
due to context change. Upstream's hunk does not carry the adjacent `aspm_os_control`
field present on this branch. The patch content itself is unchanged.

# Testing

- Clean build of both `nvidia` and `nvidia-64k` flavors
- Booted `nvidia-64k` on a GH200 running Ubuntu 26.04
- No regressions found through dmesg

LP: https://bugs.launchpad.net/bugs/2167041

### CODE REVIEW

**Comment by nirmoy** [comment]
## BaseOS Kernel Review

> [!WARNING]
> ### ⚠️ Review needs attention
> VFIO PCI dma-buf cleanup can repeat a revoke, underflow the kref, and hang device close indefinitely. The dma-buf API documentation also incorrectly limits invalidation to buffer movement.
>
> **Findings:** Critical **0** · High **1** · Medium **0** · Low **3**

### 🔍 Review artifacts

- 🟠 **Boro review:** [4 findings](https://baseos-internal-tools.nvidia.com:4001/reviews/NVIDIA/NV-Kernels/584/latest.html)
- 🔵 **Test plan:** [ready for validation](https://baseos-internal-tools.nvidia.com:4001/reviews/NVIDIA/NV-Kernels/584/test-plan.html)

### 📦 Kernel deb builds — 🟡 in progress (0/2 passed)

- 🟡 **`amd64`:** building · [live build log](https://baseos-internal-tools.nvidia.com:4001/reviews/NVIDIA/NV-Kernels/584/debs/amd64/build-log.txt)
- 🟡 **`arm64`:** building · [live build log](https://baseos-internal-tools.nvidia.com:4001/reviews/NVIDIA/NV-Kernels/584/debs/arm64/build-log.txt)

> [!NOTE]
> Build reports and debs are retained for 10 days after the PR closes.

<details>
<summary><strong>Review metadata</strong></summary>

- Reviewed head: `e12d58684dca`
- Overall status: **attention needed**
- Architectures: **0/2 successful**

</details>

_This comment is maintained by BaseOS Reviewer and updated when the GitHub watcher publishes a newer review._

**Comment by jamieNguyenNVIDIA** [comment]
`Acked-by: Jamie Nguyen <jamien@nvidia.com>`

**Review by clsotog — APPROVED** [review]
`Acked-by: Carol L Soto <csoto@nvidia.com>`

**Comment by clsotog** [comment]
Hey @kelsey-steele 
small nit somehow I see an extra line at the commits like for example:
   ```
 Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>
    
    (cherry picked from commit 5f3fc0ad9a41883a62098359b9fdbe4257f20e53)
    Signed-off-by: Kelsey Steele <kelseys@nvidia.com>

```
I see the same at the other PRs.

**Comment by kelsey-steele** [comment]
@clsotog ah, I was following a pattern from some previous backports and didn't think much of it before. Removed the line throughout all 3 PRs. Thank you for the review! :)

**Comment by clsotog** [comment]
> @clsotog ah, I was following a pattern from some previous backports and didn't think much of it before. Removed the line throughout all 3 PRs. Thank you for the review! :)

thanks 
`Acked-by: Carol L Soto <csoto@nvidia.com>`

**Comment by nvmochs** [comment]
Merged, closing PR.

```
b2db142cd58c (nresolute/main-next) iommufd: Reject DMABUF pages from the access pin path
48974aacb165 iommufd/selftest: Fix dmabuf leak in iommufd_test_dmabuf_get()
fe8f0589f63b vfio/pci: fix dma-buf kref underflow after revoke
6261f7aed2f2 iommufd: Clarify IOAS_MAP_FILE dma-buf support
634fecd7ed1f iommufd: Destroy the pages content after detaching from dmabuf
e0c31ece093d PCI/P2PDMA: Avoid returning a provider for non_mappable_bars
cd5b329c0c9e vfio: Wait for dma-buf invalidation to complete
7ea0e35fea95 RDMA/uverbs: Update for semantic conflict with drm-misc
fa22eebab4fc dma-buf: Rename dma_buf_move_notify() to dma_buf_invalidate_mappings()
```
